name: Update Fantasy5 Crossmatch JSON

on:
  schedule:
    - cron: '0 21 * * *'  # 每天 UTC 21:00 = 台灣時間 05:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python update_crossmatch.py

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ttll_crossmatch.json
          git commit -m "Auto-update crossmatch JSON"
          git push
